# Generated by Django 6.0.2 on 2026-03-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Назва')),
                ('category', models.CharField(db_index=True, max_length=80, verbose_name='Категорія (slug)')),
                ('subcategory', models.CharField(db_index=True, max_length=80, verbose_name='Підкатегорія (slug)')),
                ('price', models.PositiveIntegerField(verbose_name='Ціна (грн)')),
                ('old_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Стара ціна (грн)')),
                ('image', models.CharField(default='🚿', max_length=20, verbose_name='Зображення (emoji або URL)')),
                ('badge', models.CharField(blank=True, max_length=50, null=True, verbose_name='Бейдж (Хіт, Знижка тощо)')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наявності')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Кількість')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок сортування')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='WORLD OF Santehnika', max_length=200, verbose_name='Назва магазину')),
                ('phone', models.CharField(default='+38 (050) 123-45-67', max_length=50, verbose_name='Телефон')),
                ('hero_title', models.CharField(default='Преміальна сантехніка для вашого дому', max_length=300, verbose_name='Заголовок hero')),
                ('hero_subtitle', models.CharField(default='Італійський дизайн, німецька якість. Безплатна доставка при замовленні від 10 000 грн', max_length=500, verbose_name='Підзаголовок hero')),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
            },
        ),
    ]
