# Generated by Django 6.0.2 on 2026-03-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_add_rating_and_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_subcategory',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80, verbose_name='Під-підкатегорія (slug)'),
        ),
    ]
