# Generated by Django 6.0.2 on 2026-03-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_sub_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(default='🚿', max_length=500, verbose_name='Зображення (emoji або URL)'),
        ),
    ]
