# Generated by Django 5.2.11 on 2026-03-03 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_extend_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Ключ')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Створено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_api_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API токен',
                'verbose_name_plural': 'API токени',
            },
        ),
    ]
