# -*- coding: utf-8 -*-
"""Дані товарів та підкатегорій для WORLD OF Santehnika."""

PRODUCTS = [
    # Змішувачі кухня
    {"id": 1, "name": "Змішувач Grohe Essence Chrome", "category": "faucets", "subcategory": "kitchen-faucet", "sub_subcategory": "chrome", "price": 4490, "oldPrice": 5620, "image": "🚿", "badge": "Хіт", "description": "Змішувач Grohe Essence Chrome - найбільш популярний вибір для сучасної кухні. Хромована латунь, керамічний картридж. Гарантія 5 років."},
    {"id": 2, "name": "Змішувач Hansgrohe Talis S Black", "category": "faucets", "subcategory": "kitchen-faucet", "sub_subcategory": "black", "price": 5490, "oldPrice": None, "image": "🚿", "badge": "Преміум", "description": "Преміум змішувач з матовим чорним покриттям. Екологічна система заощадження води."},
    {"id": 3, "name": "Змішувач Ideal Standard Cerasprint", "category": "faucets", "subcategory": "kitchen-faucet", "sub_subcategory": "chrome", "price": 2290, "oldPrice": 2870, "image": "🚿", "badge": "Знижка", "description": "Економічний варіант від британського виробника. Гарантія 5 років.", "in_stock": False, "quantity": 0},
    {"id": 4, "name": "Змішувач Kludi Zenta Inox", "category": "faucets", "subcategory": "kitchen-faucet", "sub_subcategory": "inox", "price": 3890, "oldPrice": 4860, "image": "🚿", "badge": None, "description": "Німецький змішувач з нержавіючої сталі. Сучасний дизайн та надійність."},
    {"id": 5, "name": "Змішувач Roca T-2000 Kitchen", "category": "faucets", "subcategory": "kitchen-faucet", "price": 3290, "oldPrice": 4120, "image": "🚿", "badge": "Популярно", "description": "Іспанський змішувач з перевіреною надійністю. Регульована аерація."},
    {"id": 6, "name": "Змішувач Blanco Lens Chrome", "category": "faucets", "subcategory": "kitchen-faucet", "sub_subcategory": "chrome", "price": 4990, "oldPrice": 6240, "image": "🚿", "badge": None, "description": "Хромований змішувач від німецького бренду Blanco."},
    {"id": 7, "name": "Змішувач Franke Planar Black", "category": "faucets", "subcategory": "kitchen-faucet", "sub_subcategory": "black", "price": 5890, "oldPrice": 7360, "image": "🚿", "badge": "Хіт", "description": "Чорний змішувач від швейцарського виробника. Матова поверхня."},
    {"id": 8, "name": "Змішувач Teka Stradivari Inox", "category": "faucets", "subcategory": "kitchen-faucet", "sub_subcategory": "inox", "price": 7490, "oldPrice": 9360, "image": "🚿", "badge": None, "description": "Люксовий змішувач з нержавіючої сталі."},
    {"id": 9, "name": "Змішувач Schütte Grohe Style", "category": "faucets", "subcategory": "kitchen-faucet", "price": 2890, "oldPrice": 3610, "image": "🚿", "badge": "Знижка", "description": "Доступний варіант з надійною конструкцією.", "in_stock": False, "quantity": 0},
    {"id": 10, "name": "Змішувач Villeroy & Boch Como", "category": "faucets", "subcategory": "kitchen-faucet", "price": 5290, "oldPrice": 6610, "image": "🚿", "badge": "Популярно", "description": "Класичний дизайн від німецького люксового бренду."},
    {"id": 11, "name": "Змішувач Duravit Viu Black", "category": "faucets", "subcategory": "kitchen-faucet", "price": 6890, "oldPrice": 8610, "image": "🚿", "badge": "Преміум", "description": "Мінімалістичний дизайн у чорному кольорі. Німецька якість."},
    {"id": 12, "name": "Змішувач Oras Pro", "category": "faucets", "subcategory": "kitchen-faucet", "price": 5090, "oldPrice": 6360, "image": "🚿", "badge": None, "description": "Фінський змішувач з екологічними технологіями."},
    {"id": 13, "name": "Змішувач Werit Galaxy Kitchen", "category": "faucets", "subcategory": "kitchen-faucet", "price": 3990, "oldPrice": 4990, "image": "🚿", "badge": "Хіт", "description": "Популярний змішувач. Оптимальна ціна-якість."},
    {"id": 14, "name": "Змішувач Zucchetti Bamboo", "category": "faucets", "subcategory": "kitchen-faucet", "price": 8290, "oldPrice": 10360, "image": "🚿", "badge": "Люкс", "description": "Люксовий змішувач. Італійське мистецтво."},
    # Змішувачі ванна
    {"id": 15, "name": "Змішувач для ванни Grohe Eurosmart", "category": "faucets", "subcategory": "bathroom-faucet", "sub_subcategory": "chrome", "price": 3690, "oldPrice": 4610, "image": "🚿", "badge": None, "description": "Настільний змішувач для ванни. Німецька якість."},
    {"id": 16, "name": "Змішувач Hansgrohe Talis E", "category": "faucets", "subcategory": "bathroom-faucet", "sub_subcategory": "chrome", "price": 4290, "oldPrice": 5360, "image": "🚿", "badge": "Популярно", "description": "Елегантний змішувач для умивальника та ванни."},
    {"id": 17, "name": "Змішувач Ideal Standard Myno", "category": "faucets", "subcategory": "bathroom-faucet", "sub_subcategory": "compact", "price": 2490, "oldPrice": 3110, "image": "🚿", "badge": "Знижка", "description": "Компактний змішувач. Британський виробник."},
    {"id": 18, "name": "Змішувач Roca Victoria", "category": "faucets", "subcategory": "bathroom-faucet", "price": 2990, "oldPrice": 3740, "image": "🚿", "badge": None, "description": "Класичний дизайн. Іспанська надійність."},
    {"id": 19, "name": "Змішувач Kludi Mena", "category": "faucets", "subcategory": "bathroom-faucet", "price": 3490, "oldPrice": 4360, "image": "🚿", "badge": "Хіт", "description": "Сучасний змішувач для ванної кімнати."},
    {"id": 20, "name": "Змішувач Jacob Delafon Pix", "category": "faucets", "subcategory": "bathroom-faucet", "price": 4190, "oldPrice": 5240, "image": "🚿", "badge": None, "description": "Французька елегантність для ванної."},
    # Унітази
    {"id": 41, "name": "Унітаз Roca Gap Rimless", "category": "toilet", "subcategory": "wall-mounted", "sub_subcategory": "rimless", "price": 5290, "oldPrice": 6610, "image": "🚽", "badge": "Новинка", "description": "Унітаз без обідка (rimless) для легкого чищення. Іспанська якість."},
    {"id": 42, "name": "Унітаз Grohe Euro Ceramic", "category": "toilet", "subcategory": "wall-mounted", "sub_subcategory": "standard", "price": 4890, "oldPrice": 6110, "image": "🚽", "badge": "Популярно", "description": "Популярний вибір. Німецька якість. Тиха робота."},
    {"id": 43, "name": "Унітаз Villeroy & Boch ViClean", "category": "toilet", "subcategory": "wall-mounted", "sub_subcategory": "with-bidet", "price": 8490, "oldPrice": 10610, "image": "🚽", "badge": "Преміум", "description": "Люксовий унітаз з вбудованою біде функцією."},
    {"id": 44, "name": "Унітаз Duravit ME by Starck", "category": "toilet", "subcategory": "wall-mounted", "price": 9790, "oldPrice": 12240, "image": "🚽", "badge": "Люкс", "description": "Дизайнерський унітаз. Скульптурна форма."},
    {"id": 45, "name": "Унітаз Ideal Standard i.life A", "category": "toilet", "subcategory": "wall-mounted", "price": 3990, "oldPrice": 4990, "image": "🚽", "badge": "Хіт", "description": "Бестселер британської компанії."},
    {"id": 46, "name": "Унітаз Jacob Delafon Vox", "category": "toilet", "subcategory": "wall-mounted", "price": 4690, "oldPrice": 5860, "image": "🚽", "badge": None, "description": "Французька елегантність у простій формі."},
    {"id": 47, "name": "Унітаз Laufen Pro Rimless", "category": "toilet", "subcategory": "wall-mounted", "price": 3690, "oldPrice": 4610, "image": "🚽", "badge": "Знижка", "description": "Бюджетний rimless унітаз. Швейцарська якість."},
    {"id": 48, "name": "Унітаз Teka Ceramica", "category": "toilet", "subcategory": "wall-mounted", "price": 3290, "oldPrice": 4110, "image": "🚽", "badge": None, "description": "Простий та надійний іспанський унітаз."},
    {"id": 49, "name": "Унітаз Roca Meridian напольний", "category": "toilet", "subcategory": "floor-mounted", "price": 4190, "oldPrice": 5240, "image": "🚽", "badge": "Популярно", "description": "Напольний унітаз. Класична форма."},
    {"id": 50, "name": "Унітаз Grohe Sensia напольний", "category": "toilet", "subcategory": "floor-mounted", "price": 5590, "oldPrice": 6990, "image": "🚽", "badge": None, "description": "Напольний унітаз з сучасним дизайном."},
    {"id": 51, "name": "Унітаз Ideal Standard Connect", "category": "toilet", "subcategory": "floor-mounted", "price": 3490, "oldPrice": 4360, "image": "🚽", "badge": "Знижка", "description": "Економний напольний унітаз."},
    {"id": 52, "name": "Унітаз Toto Neorest Bidet", "category": "toilet", "subcategory": "wall-mounted", "price": 24990, "oldPrice": 31240, "image": "🚽", "badge": "Люкс", "description": "Люксовий японський унітаз з функцією біде.", "in_stock": False, "quantity": 0},
    # Ванна - раковини
    {"id": 108, "name": "Раковина Laufen Pro 60см", "category": "bathroom", "subcategory": "sink", "sub_subcategory": "60cm", "price": 1690, "oldPrice": 2120, "image": "🪥", "badge": "Хіт", "description": "Якісна раковина 60 см. Швейцарська якість."},
    {"id": 109, "name": "Раковина Jacob Delafon Formilia", "category": "bathroom", "subcategory": "sink", "sub_subcategory": "65cm", "price": 2990, "oldPrice": 3740, "image": "🪥", "badge": "Популярно", "description": "Раковина від французького виробника."},
    {"id": 110, "name": "Раковина Duravit D-Code 65см", "category": "bathroom", "subcategory": "sink", "sub_subcategory": "65cm", "price": 2490, "oldPrice": 3120, "image": "🪥", "badge": None, "description": "Сучасна раковина 65 см."},
    {"id": 111, "name": "Раковина Villeroy & Boch Legato", "category": "bathroom", "subcategory": "sink", "sub_subcategory": "70cm", "price": 3890, "oldPrice": 4860, "image": "🪥", "badge": "Преміум", "description": "Елегантна раковина. Німецький бренд."},
    {"id": 112, "name": "Раковина Grohe Cube 70см", "category": "bathroom", "subcategory": "sink", "sub_subcategory": "70cm", "price": 2890, "oldPrice": 3610, "image": "🪥", "badge": "Новинка", "description": "Раковина з сучасним дизайном."},
    {"id": 113, "name": "Раковина Roca Happening 60см", "category": "bathroom", "subcategory": "sink", "price": 1990, "oldPrice": 2490, "image": "🪥", "badge": None, "description": "Компактна раковина для невеликої ванної."},
    {"id": 114, "name": "Раковина Blanco Linea 65см", "category": "bathroom", "subcategory": "sink", "price": 2590, "oldPrice": 3240, "image": "🪥", "badge": "Хіт", "description": "Німецька якість за доступною ціною."},
    {"id": 115, "name": "Раковина Hansgrohe Metropol 70см", "category": "bathroom", "subcategory": "sink", "price": 3290, "oldPrice": 4110, "image": "🪥", "badge": "Преміум", "description": "Преміум раковина з інноваційним дизайном."},
    # Ванна - душ
    {"id": 116, "name": "Душова кабіна Grohe Vitalio", "category": "bathroom", "subcategory": "shower", "price": 12990, "oldPrice": 16240, "image": "🚿", "badge": "Хіт", "description": "Кутова душова кабіна. Склопакет, піддон."},
    {"id": 117, "name": "Душова кабіна Roca Ona", "category": "bathroom", "subcategory": "shower", "price": 8990, "oldPrice": 11240, "image": "🚿", "badge": "Популярно", "description": "Прямокутна душова кабіна. Іспанська якість."},
    {"id": 118, "name": "Душова кабіна Ideal Standard", "category": "bathroom", "subcategory": "shower", "price": 7490, "oldPrice": 9360, "image": "🚿", "badge": None, "description": "Компактна душова кабіна для малих ванних."},
    {"id": 119, "name": "Душова система Hansgrohe Raindance", "category": "bathroom", "subcategory": "shower", "price": 8490, "oldPrice": 10610, "image": "🚿", "badge": "Преміум", "description": "Верхній душ з ефектом дощу."},
    {"id": 120, "name": "Душова панель Kludi E2", "category": "bathroom", "subcategory": "shower", "price": 4590, "oldPrice": 5740, "image": "🚿", "badge": "Знижка", "description": "Настінна душова панель з лейкою."},
    # Кухня - мійки
    {"id": 138, "name": "Кухонна мійка Blando Andano 180", "category": "kitchen", "subcategory": "sink", "sub_subcategory": "two-bowl", "price": 7890, "oldPrice": 9860, "image": "🍽️", "badge": "Хіт", "description": "Кухонна мійка 180 см. Нержавіюча сталь."},
    {"id": 139, "name": "Кухонна мійка Franke Planar Box", "category": "kitchen", "subcategory": "sink", "sub_subcategory": "one-bowl", "price": 6290, "oldPrice": 7860, "image": "🍽️", "badge": "Популярно", "description": "Мійка з сушаркою. Швейцарська якість."},
    {"id": 140, "name": "Кухонна мійка Teka Stradivari", "category": "kitchen", "subcategory": "sink", "sub_subcategory": "two-bowl", "price": 8790, "oldPrice": 10980, "image": "🍽️", "badge": "Преміум", "description": "Преміум кухонна мійка. Іспанський виробник."},
    {"id": 141, "name": "Кухонна мійка Grohe Sink K700", "category": "kitchen", "subcategory": "sink", "price": 9890, "oldPrice": 12360, "image": "🍽️", "badge": "Новинка", "description": "Інноваційна мійка з інтегрованим змішувачем."},
    {"id": 142, "name": "Кухонна мійка Roca Crystalline", "category": "kitchen", "subcategory": "sink", "price": 5490, "oldPrice": 6860, "image": "🍽️", "badge": None, "description": "Мійка з кварцового композиту."},
    {"id": 143, "name": "Кухонна мійка Blanco Livit", "category": "kitchen", "subcategory": "sink", "price": 7890, "oldPrice": 9860, "image": "🍽️", "badge": "Популярно", "description": "Подвійна мійка. Німецька сталь."},
    {"id": 144, "name": "Кухонна мійка Schütte Standard", "category": "kitchen", "subcategory": "sink", "price": 2890, "oldPrice": 3610, "image": "🍽️", "badge": "Знижка", "description": "Економна кухонна мійка. Надійна конструкція."},
    {"id": 145, "name": "Кухонна мійка Jacob Delafon Evier", "category": "kitchen", "subcategory": "sink", "price": 4890, "oldPrice": 6110, "image": "🍽️", "badge": None, "description": "Елегантна мійка. Французький дизайн."},
    {"id": 146, "name": "Кухонна мійка Laufen Pro Box", "category": "kitchen", "subcategory": "sink", "price": 4290, "oldPrice": 5360, "image": "🍽️", "badge": "Хіт", "description": "Компактна мійка з сушаркою."},
    # Кухня - стільниці
    {"id": 147, "name": "Стільниця для мійки Blanco", "category": "kitchen", "subcategory": "countertop", "price": 3490, "oldPrice": 4360, "image": "🍽️", "badge": None, "description": "Стільниця з нержавійки під вбудову мійки."},
    {"id": 148, "name": "Стільниця Franke для мійки", "category": "kitchen", "subcategory": "countertop", "price": 4190, "oldPrice": 5240, "image": "🍽️", "badge": "Популярно", "description": "Стільниця з сушаркою. Швейцарська якість."},
    {"id": 149, "name": "Стільниця Roca Continental", "category": "kitchen", "subcategory": "countertop", "price": 2690, "oldPrice": 3360, "image": "🍽️", "badge": "Знижка", "description": "Економна стільниця під мійку."},
    # Басейн
    {"id": 183, "name": "Басейновий ліхтар LED RGB", "category": "pool", "subcategory": "lighting", "sub_subcategory": "led", "price": 3290, "oldPrice": 4110, "image": "🏊", "badge": "Новинка", "description": "Підводний LED ліхтар з кольоровою підсвіткою."},
    {"id": 184, "name": "Прожектор підводний Intex", "category": "pool", "subcategory": "lighting", "sub_subcategory": "led", "price": 1890, "oldPrice": 2360, "image": "💡", "badge": "Популярно", "description": "Надійний підводний прожектор для басейну."},
    {"id": 185, "name": "Лампа галогенна для басейну", "category": "pool", "subcategory": "lighting", "sub_subcategory": "halogen", "price": 890, "oldPrice": 1110, "image": "💡", "badge": None, "description": "Галогенна лампа для освітлення басейну."},
    {"id": 186, "name": "LED світильник вбудований басейн", "category": "pool", "subcategory": "lighting", "price": 2490, "oldPrice": 3110, "image": "💡", "badge": "Хіт", "description": "Вбудований LED світильник для басейну."},
    {"id": 187, "name": "Насос для басейну Intex", "category": "pool", "subcategory": "pump", "price": 4290, "oldPrice": 5360, "image": "🏊", "badge": "Популярно", "description": "Циркуляційний насос для фільтрації води."},
    {"id": 188, "name": "Насос для басейну Bestway", "category": "pool", "subcategory": "pump", "price": 3590, "oldPrice": 4490, "image": "🏊", "badge": None, "description": "Потужний насос для каркасних басейнів."},
    {"id": 189, "name": "Фільтр-насос для басейну", "category": "pool", "subcategory": "pump", "price": 5490, "oldPrice": 6860, "image": "🏊", "badge": "Преміум", "description": "Комбінований фільтр-насос. Пісочний фільтр."},
    {"id": 190, "name": "Система фільтрації басейну", "category": "pool", "subcategory": "filtration", "price": 8990, "oldPrice": 11240, "image": "🏊", "badge": "Хіт", "description": "Повноцінна система фільтрації для басейну."},
    {"id": 191, "name": "Пісочний фільтр 400мм", "category": "pool", "subcategory": "filtration", "price": 4290, "oldPrice": 5360, "image": "🏊", "badge": None, "description": "Пісочний фільтр для невеликих басейнів."},
    {"id": 192, "name": "Покривало для басейну", "category": "pool", "subcategory": "cover", "price": 1890, "oldPrice": 2360, "image": "🏊", "badge": "Популярно", "description": "Термо покривало для збереження тепла води."},
    {"id": 193, "name": "Скло для басейну", "category": "pool", "subcategory": "cover", "price": 3490, "oldPrice": 4360, "image": "🏊", "badge": None, "description": "Рулонне покривало з полікарбонату."},
    # Опалення
    {"id": 247, "name": "Радіатор Kermi 2000x600", "category": "heating", "subcategory": "radiator", "sub_subcategory": "panel", "price": 9890, "oldPrice": 12360, "image": "🔥", "badge": "Хіт", "description": "Радіатор опалення 2000x600 мм. Німецька якість."},
    {"id": 248, "name": "Радіатор Vogel&Noot", "category": "heating", "subcategory": "radiator", "sub_subcategory": "panel", "price": 7490, "oldPrice": 9360, "image": "🔥", "badge": "Преміум", "description": "Якісний радіатор опалення."},
    {"id": 249, "name": "Радіатор Buderus 2000x600", "category": "heating", "subcategory": "radiator", "sub_subcategory": "panel", "price": 8290, "oldPrice": 10360, "image": "🔥", "badge": "Популярно", "description": "Радіатор Buderus. Перевірений виробник."},
    {"id": 250, "name": "Радіатор Ferroli 1800x600", "category": "heating", "subcategory": "radiator", "price": 6490, "oldPrice": 8110, "image": "🔥", "badge": None, "description": "Радіатор 1800x600. Італійський бренд."},
    {"id": 251, "name": "Радіатор Stelrad 2000x700", "category": "heating", "subcategory": "radiator", "price": 9290, "oldPrice": 11610, "image": "🔥", "badge": "Популярно", "description": "Панельний радіатор. Європейська якість."},
    {"id": 252, "name": "Радіатор Thermea 1600x600", "category": "heating", "subcategory": "radiator", "price": 5890, "oldPrice": 7360, "image": "🔥", "badge": "Хіт", "description": "Компактний радіатор для малих кімнат."},
    {"id": 253, "name": "Радіатор ARBONIA 1200x600", "category": "heating", "subcategory": "radiator", "sub_subcategory": "tubular", "price": 4890, "oldPrice": 6110, "image": "🔥", "badge": "Знижка", "description": "Трубчастий радіатор. Дизайнерський вигляд."},
    {"id": 254, "name": "Котел газовий Ferroli 24 кВт", "category": "heating", "subcategory": "boiler", "price": 24990, "oldPrice": 31240, "image": "🔥", "badge": "Хіт", "description": "Настінний газовий котел. Двоконтурний."},
    {"id": 255, "name": "Котел газовий Baxi 28 кВт", "category": "heating", "subcategory": "boiler", "price": 28990, "oldPrice": 36240, "image": "🔥", "badge": "Преміум", "description": "Потужний газовий котел для будинку."},
    {"id": 256, "name": "Котел газовий Vaillant 24 кВт", "category": "heating", "subcategory": "boiler", "price": 32990, "oldPrice": 41240, "image": "🔥", "badge": "Люкс", "description": "Преміум газовий котел. Німецька якість."},
    {"id": 257, "name": "Терморегулятор Danfoss", "category": "heating", "subcategory": "thermostat", "price": 1290, "oldPrice": 1610, "image": "🔥", "badge": "Популярно", "description": "Електронний терморегулятор для радіатора."},
    {"id": 258, "name": "Терморегулятор Oventrop", "category": "heating", "subcategory": "thermostat", "price": 890, "oldPrice": 1110, "image": "🔥", "badge": None, "description": "Термостатична голівка для радіатора."},
    {"id": 259, "name": "Тепла підлога Rehau", "category": "heating", "subcategory": "floor-heating", "price": 3490, "oldPrice": 4360, "image": "🔥", "badge": "Новинка", "description": "Комплект для теплої підлоги. 50 м²."},
    {"id": 260, "name": "Тепла підлога Uponor", "category": "heating", "subcategory": "floor-heating", "price": 4290, "oldPrice": 5360, "image": "🔥", "badge": "Преміум", "description": "Труби для теплої підлоги. Європейський стандарт."},
    # Аксесуари
    {"id": 301, "name": "Герметик санітарний Soudal", "category": "accessories", "subcategory": "sealants", "price": 189, "oldPrice": 236, "image": "⚙️", "badge": "Хіт", "description": "Санітарний силіконовий герметик. Білий."},
    {"id": 302, "name": "Герметик Ceresit CS 25", "category": "accessories", "subcategory": "sealants", "price": 249, "oldPrice": 311, "image": "⚙️", "badge": None, "description": "Універсальний санітарний герметик.", "in_stock": False, "quantity": 0},
    {"id": 303, "name": "Килимок ванний Grohe", "category": "accessories", "subcategory": "mats", "price": 890, "oldPrice": 1110, "image": "⚙️", "badge": "Популярно", "description": "Антиковзний килимок перед ванною."},
    {"id": 304, "name": "Килимок ванний Roca", "category": "accessories", "subcategory": "mats", "price": 690, "oldPrice": 860, "image": "⚙️", "badge": None, "description": "М'який килимок. Декор під кахель."},
    {"id": 305, "name": "Держач для зубних щіток", "category": "accessories", "subcategory": "holders", "price": 490, "oldPrice": 610, "image": "⚙️", "badge": None, "description": "Настінний держач для щіток та склянки."},
    {"id": 306, "name": "Полиця ванна настінна", "category": "accessories", "subcategory": "holders", "price": 1290, "oldPrice": 1610, "image": "⚙️", "badge": "Знижка", "description": "Металічна полиця з покриттям під хром."},
    {"id": 307, "name": "Дзеркало з підсвіткою 60см", "category": "accessories", "subcategory": "mirrors", "price": 3490, "oldPrice": 4360, "image": "⚙️", "badge": "Популярно", "description": "Дзеркало для ванної з LED підсвіткою."},
    {"id": 308, "name": "Дзеркало Roca з шухлядою", "category": "accessories", "subcategory": "mirrors", "price": 4290, "oldPrice": 5360, "image": "⚙️", "badge": "Хіт", "description": "Дзеркало-шафа з вбудованою шухлядою."},
    {"id": 309, "name": "Кріплення для радіатора", "category": "accessories", "subcategory": "hardware", "price": 290, "oldPrice": 360, "image": "⚙️", "badge": None, "description": "Набір кронштейнів для настінного радіатора."},
    {"id": 310, "name": "Шланг підведення 50см", "category": "accessories", "subcategory": "hardware", "price": 390, "oldPrice": 490, "image": "⚙️", "badge": None, "description": "Гнучкий шланг підведення води."},
    # Ванни
    {"id": 401, "name": "Ванна акрилова Roca Victoria 170", "category": "bath", "subcategory": "acrylic-bath", "sub_subcategory": "acrylic", "price": 12990, "oldPrice": 16240, "image": "🛁", "badge": "Хіт", "description": "Акрилова ванна 170 см. Міцна, легка. Іспанська якість."},
    {"id": 402, "name": "Ванна акрилова Cersanit Simple 160", "category": "bath", "subcategory": "acrylic-bath", "sub_subcategory": "acrylic", "price": 8990, "oldPrice": 11240, "image": "🛁", "badge": "Знижка", "description": "Компактна акрилова ванна 160 см. Польський виробник."},
    {"id": 403, "name": "Ванна акрилова Jacob Delafon Louvre 180", "category": "bath", "subcategory": "acrylic-bath", "sub_subcategory": "acrylic", "price": 15990, "oldPrice": 19990, "image": "🛁", "badge": "Преміум", "description": "Преміум акрилова ванна 180 см. Французький дизайн."},
    {"id": 404, "name": "Ванна сталева Kaldewei Saniform Plus 170", "category": "bath", "subcategory": "steel-bath", "sub_subcategory": "steel", "price": 24990, "oldPrice": 31240, "image": "🛁", "badge": "Преміум", "description": "Емальована сталева ванна. Німецька якість. Гарантія 30 років."},
    {"id": 405, "name": "Ванна сталева Roca Madrid 170", "category": "bath", "subcategory": "steel-bath", "price": 11990, "oldPrice": 14990, "image": "🛁", "badge": None, "description": "Сталева емальована ванна. Класична форма."},
    {"id": 406, "name": "Ванна кутова акрилова 150", "category": "bath", "subcategory": "corner-bath", "price": 14990, "oldPrice": 18740, "image": "🛁", "badge": "Популярно", "description": "Кутова ванна для економії місця. Підходить для кутового монтажу."},
    {"id": 407, "name": "Ванна кутова Cersanit Kolo 160", "category": "bath", "subcategory": "corner-bath", "price": 16990, "oldPrice": 21240, "image": "🛁", "badge": "Новинка", "description": "Дизайнерська кутова ванна. Овальна форма."},
    # Бойлери
    {"id": 501, "name": "Бойлер Ariston ABS VLS 80", "category": "water-heaters", "subcategory": "electric-boiler", "sub_subcategory": "electric", "price": 8990, "oldPrice": 11240, "image": "💧", "badge": "Хіт", "description": "Електричний бойлер 80 л. Вертикальний. Сухий ТЕН."},
    {"id": 502, "name": "Бойлер Thermex Champion 100", "category": "water-heaters", "subcategory": "electric-boiler", "sub_subcategory": "electric", "price": 6490, "oldPrice": 8110, "image": "💧", "badge": "Знижка", "description": "Електричний бойлер 100 л. Економний варіант.", "in_stock": False, "quantity": 0},
    {"id": 503, "name": "Бойлер Gorenje OT 80", "category": "water-heaters", "subcategory": "electric-boiler", "sub_subcategory": "electric", "price": 7290, "oldPrice": 9110, "image": "💧", "badge": None, "description": "Бойлер 80 л. Словенський виробник. Надійність."},
    {"id": 504, "name": "Газовий колонка Bosch WR 10-2P", "category": "water-heaters", "subcategory": "gas-boiler", "sub_subcategory": "gas", "price": 12990, "oldPrice": 16240, "image": "💧", "badge": "Популярно", "description": "Газова проточная колонка. Економія газу."},
    {"id": 505, "name": "Газовий колонка Ariston Fast Evo 11B", "category": "water-heaters", "subcategory": "gas-boiler", "price": 9990, "oldPrice": 12490, "image": "💧", "badge": None, "description": "Компактна газова колонка. Під запаленням від батарейок."},
    {"id": 506, "name": "Накопичувач Gorenje TGU 100", "category": "water-heaters", "subcategory": "storage", "price": 14990, "oldPrice": 18740, "image": "💧", "badge": "Преміум", "description": "Накопичувальний бойлер непрямого нагріву 100 л. Для котла."},
    {"id": 507, "name": "Накопичувач Drazice OKC 200", "category": "water-heaters", "subcategory": "storage", "price": 24990, "oldPrice": 31240, "image": "💧", "badge": "Преміум", "description": "Бойлер непрямого нагріву 200 л. Чеська якість."},
    # Труби та каналізація
    {"id": 601, "name": "Труба PP-R 25мм 4м", "category": "pipes", "subcategory": "pipes", "price": 189, "oldPrice": 236, "image": "🔧", "badge": None, "description": "Поліпропіленова труба для гарячої та холодної води."},
    {"id": 602, "name": "Труба PP-R 32мм 4м", "category": "pipes", "subcategory": "pipes", "price": 279, "oldPrice": 349, "image": "🔧", "badge": "Хіт", "description": "Труба PP-R 32 мм. Для стояків та розводки."},
    {"id": 603, "name": "Труба металопластик 20x2мм 50м", "category": "pipes", "subcategory": "pipes", "price": 2490, "oldPrice": 3110, "image": "🔧", "badge": None, "description": "Металопластикова труба в бухті. Для підлогового опалення та розводки."},
    {"id": 604, "name": "Каналізаційна труба PVC 110мм 1м", "category": "pipes", "subcategory": "drains", "price": 349, "oldPrice": 436, "image": "🔧", "badge": None, "description": "Каналізаційна труба ПВХ 110 мм. Для стояків."},
    {"id": 605, "name": "Каналізаційна труба PVC 50мм 1м", "category": "pipes", "subcategory": "drains", "price": 149, "oldPrice": 186, "image": "🔧", "badge": None, "description": "Труба ПВХ 50 мм для горизонтальної каналізації."},
    {"id": 606, "name": "Фітинг PP-R кут 90° 25мм", "category": "pipes", "subcategory": "fittings", "price": 49, "oldPrice": 61, "image": "🔧", "badge": None, "description": "Кутовий фітинг для поліпропіленових труб."},
    {"id": 607, "name": "Фітинг PP-R трійник 25мм", "category": "pipes", "subcategory": "fittings", "price": 69, "oldPrice": 86, "image": "🔧", "badge": "Хіт", "description": "Трійник для розводки води."},
    {"id": 608, "name": "Сифон під умивальник", "category": "pipes", "subcategory": "fittings", "price": 390, "oldPrice": 490, "image": "🔧", "badge": None, "description": "Сифон хромований з переливом. Універсальний."},
    {"id": 609, "name": "Ревізія каналізаційна 110мм", "category": "pipes", "subcategory": "drains", "price": 299, "oldPrice": 374, "image": "🔧", "badge": None, "description": "Ревізійний люк для прочищення каналізації."},
]

SUBCATEGORY_LABELS = {
    "kitchen-faucet": "Змішувачі для кухні",
    "bathroom-faucet": "Змішувачі для ванни",
    "wall-mounted": "Підвісні унітази",
    "floor-mounted": "Напольні унітази",
    "sink": "Мійки та раковини",
    "shower": "Душові системи",
    "countertop": "Стільниці",
    "lighting": "Освітлення",
    "pump": "Насоси",
    "filtration": "Фільтрація",
    "cover": "Покривала",
    "radiator": "Радіатори",
    "boiler": "Котли",
    "thermostat": "Терморегулятори",
    "floor-heating": "Тепла підлога",
    "sealants": "Герметики",
    "mats": "Килимки",
    "holders": "Держачі та полиці",
    "mirrors": "Дзеркала",
    "hardware": "Кріпіж та комплектуючі",
    "acrylic-bath": "Акрилові ванни",
    "steel-bath": "Сталеві ванни",
    "corner-bath": "Кутові ванни",
    "electric-boiler": "Електричні бойлери",
    "gas-boiler": "Газові колонки",
    "storage": "Накопичувачі",
    "pipes": "Труби",
    "fittings": "Фітинги та сифони",
    "drains": "Каналізація",
}

# Під-підкатегорії (третій рівень під поточними підрозділами)
SUB_SUBCATEGORY_LABELS = {
    "chrome": "Хром",
    "black": "Чорний / матовий",
    "inox": "Нержавійка",
    "one-bowl": "Одна чаша",
    "two-bowl": "Дві чаші",
    "undermount": "Під стільницю",
    "rimless": "Без обідка",
    "with-bidet": "З біде",
    "compact": "Компактні",
    "standard": "Стандарт",
    "led": "LED",
    "halogen": "Галоген",
    "panel": "Панельні",
    "tubular": "Трубчасті",
    "wall": "Настінні",
    "floor": "Напольні",
    "electric": "Електричні",
    "gas": "Газові",
    "acrylic": "Акрилові",
    "steel": "Сталеві",
    "corner": "Кутові",
    "60cm": "до 60 см",
    "65cm": "60–70 см",
    "70cm": "70 см і більше",
}
